name: Update SevDesk API

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Update OpenAPI (SevDesk)
        run: |
          curl -fsSL https://api.sevdesk.de/openapi.yaml -o ./nodes/sevdesk/openapi.yaml
          pnpm exec js-yaml -j ./nodes/sevdesk/openapi.yaml > ./nodes/sevdesk/openapi.json

      - name: Check for changes
        id: check
        run: |
          git diff --exit-code nodes/sevdesk/openapi.json || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Bump version and commit
        if: steps.check.outputs.changed == 'true'
        run: |
          pnpm version patch --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")

          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          git add nodes/sevdesk/openapi.json package.json pnpm-lock.yaml
          git commit -m "chore: update SevDesk API"
          git push

          git tag "$VERSION"
          git push --tags
